"""
Django settings for checkngo project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
#from readline import backend
from decouple import config
from datetime import timedelta

import dj_database_url

#from analytics.tests.test_alerts import url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
#ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost").split(",")
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",     # <-- keep this one only
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "phonenumber_field",

    # Local
    "accounts",
    "farms.apps.FarmsConfig",
    "partners",
    "production.apps.ProductionConfig",
    "analytics",
    "drf_spectacular",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (incl. the admin's CSS) directly from
    # Django when DEBUG is False, so the API host needs no separate static
    # server. Must sit immediately after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'checkngo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'checkngo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Production (Render) provides a single DATABASE_URL. When it is absent we
# fall back to the discrete DB_* variables used for local development,
# unchanged — so a dev machine with no DATABASE_URL behaves exactly as before.
DATABASE_URL = config("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }

# Comma-separated in the environment. The default is the local dev/preview
# origin list, so nothing changes without CORS_ALLOWED_ORIGINS set.
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:4173,https://your-frontend-url.trycloudflare.com"
        "http://localhost:5173,"
        "http://127.0.0.1:5173,"
        "http://localhost:4173,"
        "http://127.0.0.1:4173,"
        "http://11.0.2.244:4173"
    ),
).split(",")

# Origins Django accepts for unsafe (POST) requests behind CSRF protection —
# needed for the admin login form once it is served over HTTPS on a real
# domain. Comma-separated, scheme included (e.g. https://checkngo-api.onrender.com);
# empty locally, where admin is same-origin over http.
#CSRF_TRUSTED_ORIGINS = [
#    origin.strip()
#    for origin in config("CSRF_TRUSTED_ORIGINS", default="").split(",")
#    if origin.strip()
#]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config("CSRF_TRUSTED_ORIGINS", default="").split(",")
    if origin.strip()
]

# Base URL of the frontend app. Used to build links that leave the API
# entirely — e.g. the invite-accept deep link mailed/texted to an invitee.
FRONTEND_URL = config("FRONTEND_URL", default="https://your-frontend-url.trycloudflare.com") #http://localhost:5173"

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# `collectstatic` target. WhiteNoise serves from here when DEBUG is False;
# without it the admin renders unstyled in production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 6.1 removed the STATICFILES_STORAGE setting — the equivalent is the
# "staticfiles" entry in STORAGES. CompressedManifestStaticFilesStorage adds
# content hashes and pre-compressed (gzip/brotli) copies for WhiteNoise.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "farms.permissions.HasRotatedCredential",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "phone_login": "10/hour",
        "login_ip": "30/hour",
        "invite_accept": "10/hour",
        "credential_change": "5/hour",
        "user": "1000/hour",
        "anon": "60/hour",
    },
}
# Throttle counters live in the cache. LocMemCache is per-process, so with
# multiple Gunicorn workers each keeps its own counters and the effective
# rate limits multiply by the worker count. When REDIS_URL is set we use a
# shared Redis cache; locally, with no REDIS_URL, LocMemCache is unchanged.
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "checkngo-throttle-cache",
        }
    }

CORS_ALLOW_ALL_ORIGINS = DEBUG   # tighten this before deployment

# Production hardening. Only applied when DEBUG is False, so local
# development over plain HTTP is untouched.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    # Render terminates TLS at its load balancer and forwards plain HTTP to
    # the app, setting X-Forwarded-Proto. Without this, SECURE_SSL_REDIRECT
    # never sees "https", redirects forever, and the site is dead.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),      # one farm shift
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),     # rural connectivity is intermittent
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,                # needs the blacklist app; see note
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

ADMIN_SITE_HEADER = "CheckN Go Administration"

SPECTACULAR_SETTINGS = {
    "TITLE": "CheckN Go API",
    "DESCRIPTION": (
        "Backend for CheckN Go — a cross-platform poultry management system "
        "for distributed farm coordination and descriptive analytics.\n\n"
        "**Authentication:** phone number (E.164) + PIN, returning JWT access "
        "and refresh tokens. Send `Authorization: Bearer <access>`.\n\n"
        "**Forced rotation:** a newly onboarded user has "
        "`must_change_credential = true` and is blocked from every endpoint "
        "except `/auth/me/` and `/auth/credential/change/` until they rotate "
        "their PIN.\n\n"
        "**Farm scoping:** operational endpoints are nested under "
        "`/farms/<farm_id>/`. Access is resolved from the caller's active "
        "membership on that farm; a member of one farm cannot read another's "
        "data."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {"name": "Authentication", "description": "Login, logout, PIN rotation."},
        {"name": "Invitations", "description": "Staff and partner onboarding."},
        {"name": "Farms", "description": "Farms, membership, ownership."},
        {"name": "Partners", "description": "Suppliers and buyers."},
        {"name": "Production", "description": "Houses, batches, daily records."},
        {"name": "Analytics", "description": "Charts and aggregations."},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
    },
}