# Generated by Django 6.1 on 2026-08-22 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farmownershiphistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CONSUMER', 'Consumer')], max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='farms.farm')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_links_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners_farm_link',
                'ordering': ['farm', 'link_type', 'business_name'],
                'indexes': [models.Index(fields=['partner', 'is_active'], name='link_partner_active_idx'), models.Index(fields=['farm', 'link_type'], name='link_farm_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('farm', 'partner', 'link_type'), name='unique_partner_link_per_farm_type')],
            },
        ),
    ]
