# Generated by Django 6.1 on 2026-08-22 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farmownershiphistory'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(help_text='Human-facing, e.g. B-2026-03', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('initial_bird_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HARVESTED', 'Harvested'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20)),
                ('total_mortality', models.PositiveIntegerField(default=0)),
                ('total_feed_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_batch',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('birds_harvested', models.PositiveIntegerField()),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Gross sale value. Recorded after the fact, not transacted here.', max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='production.batch')),
                ('buyer_link', models.ForeignKey(blank=True, help_text='Optional: the consumer this batch went to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests_purchased', to='partners.farmpartnerlink')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_harvest',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum birds this house can hold.', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='farms.farm')),
            ],
            options={
                'db_table': 'production_house',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.house'),
        ),
        migrations.CreateModel(
            name='WeightSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_date', models.DateField(db_index=True)),
                ('birds_weighed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('average_grams', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_samples', to='production.batch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_weight_sample',
                'ordering': ['-sample_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('mortality_disease', models.PositiveIntegerField(default=0)),
                ('mortality_heat', models.PositiveIntegerField(default=0)),
                ('mortality_culled', models.PositiveIntegerField(default=0)),
                ('mortality_unknown', models.PositiveIntegerField(default=0)),
                ('feed_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='production.batch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_daily_record',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['batch', 'record_date'], name='daily_batch_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'record_date'), name='unique_daily_record_per_batch')],
            },
        ),
        migrations.CreateModel(
            name='FeedDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(db_index=True)),
                ('feed_type', models.CharField(choices=[('STARTER', 'Starter'), ('GROWER', 'Grower'), ('FINISHER', 'Finisher'), ('OTHER', 'Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg.', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_deliveries', to='farms.farm')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('supplier_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_deliveries', to='partners.farmpartnerlink')),
            ],
            options={
                'db_table': 'production_feed_delivery',
                'ordering': ['-delivery_date'],
                'indexes': [models.Index(fields=['farm', 'delivery_date'], name='feed_farm_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_house_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['house', 'status'], name='batch_house_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date'], name='batch_start_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('house', 'batch_code'), name='unique_batch_code_per_house'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('house',), name='one_active_batch_per_house'),
        ),
        migrations.AddConstraint(
            model_name='weightsample',
            constraint=models.UniqueConstraint(fields=('batch', 'sample_date'), name='unique_weight_sample_per_day'),
        ),
    ]
