# Generated by Django 6.1 on 2026-08-23 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0002_batch_terminated_at_batch_terminated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('record_date', models.DateField(db_index=True)),
                ('previous_values', models.JSONField(help_text='Full snapshot before the change.')),
                ('new_values', models.JSONField()),
                ('changed_fields', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('corrected_by_name', models.CharField(blank=True, max_length=150)),
                ('corrected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='production.batch')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_record_correction',
                'ordering': ['-corrected_at'],
                'indexes': [models.Index(fields=['batch', '-corrected_at'], name='correction_batch_time_idx'), models.Index(fields=['content_type', 'object_id'], name='correction_target_idx')],
            },
        ),
    ]
