# Generated by Django 6.1 on 2026-09-01 17:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farmownershiphistory'),
        ('production', '0003_recordcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='How it is counted: kg, litre, sack, dose.', max_length=20)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Warn once the balance falls to or below this.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='farms.farm')),
            ],
            options={
                'db_table': 'production_inventory_item',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_in_date', models.DateField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='production.inventoryitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_inventory_stock_in',
                'ordering': ['-stock_in_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('usage_date', models.DateField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='production.inventoryitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_inventory_usage_log',
                'ordering': ['-usage_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_inventory_item_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='inventorystockin',
            index=models.Index(fields=['item', 'stock_in_date'], name='inv_stockin_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusagelog',
            index=models.Index(fields=['item', 'usage_date'], name='inv_usage_item_date_idx'),
        ),
    ]
