# Generated by Django 6.1 on 2026-09-02 07:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmmembership_houses'),
        ('production', '0004_inventoryitem_inventorystockin_inventoryusagelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('suggested_time', models.CharField(blank=True, help_text='Free text — "6:00 AM", or "after morning rounds".', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display sequence.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='farms.farm')),
            ],
            options={
                'db_table': 'production_task_template',
                'ordering': ['farm', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateField(db_index=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='production.tasktemplate')),
            ],
            options={
                'db_table': 'production_task_completion',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_task_template_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('template', 'completion_date'), name='unique_completion_per_template_day'),
        ),
    ]
