# Generated by Django 6.1 on 2026-09-03 07:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_taskcompletion_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='feed_item',
            field=models.ForeignKey(blank=True, help_text='The feed item the sacks were counted against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_feed_records', to='production.inventoryitem'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='feed_sacks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='kg_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilograms per unit, for feed items. Leave blank for items not measured by weight.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
