# Generated by Django 6.1 on 2026-09-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_dailyrecord_feed_item_dailyrecord_feed_sacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryusagelog',
            name='daily_record',
            field=models.OneToOneField(blank=True, help_text='The daily record whose feed line produced this drawdown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_usage_log', to='production.dailyrecord'),
        ),
    ]
