# Generated by Django 6.1 on 2026-09-03 17:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('production', '0008_inventoryusagelog_daily_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_birds_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_weight_sold_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='harvest',
            name='closing_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='birds_harvested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='buyer_link',
            field=models.ForeignKey(blank=True, help_text='Optional principal buyer for the batch overall. Individual sales carry no buyer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests_purchased', to='partners.farmpartnerlink'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Summed from the batch's sale events at closing time.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-supplied. When the worker actually entered this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField(db_index=True)),
                ('sale_type', models.CharField(choices=[('DRESSED', 'Dressed'), ('LIVE', 'Live')], max_length=20)),
                ('bird_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Sale value. Optional — a weight-only record is valid.', max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_events', to='production.batch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_sale_event',
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['batch', 'sale_date'], name='sale_batch_date_idx')],
            },
        ),
    ]
