# Generated by Django 6.1 on 2026-09-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_harvest_to_sale_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-start_date'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='feeddelivery',
            name='inventory_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_feed': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_deliveries', to='production.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_feed',
            field=models.BooleanField(default=False, help_text='Feed stock arrives via deliveries and leaves via daily records, not manual entries.'),
        ),
    ]
