# Generated by Django 6.1 on 2026-08-20 17:16

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +639171234567.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_role', models.CharField(choices=[('OWNER', 'Farm Owner'), ('MANAGER', 'Farm Manager'), ('WORKER', 'Farm Worker'), ('SUPPLIER', 'Supplier'), ('CONSUMER', 'Consumer')], max_length=20)),
                ('membership_role', models.CharField(blank=True, help_text='Operational role at the farm. Blank for external partners.', max_length=20)),
                ('token', models.CharField(default=accounts.models.generate_invite_token, editable=False, max_length=64, unique=True)),
                ('pin_hash', models.CharField(editable=False, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitation', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, help_text='Null for external partners, who hold no farm membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='farms.farm')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'status'], name='invite_phone_status_idx'), models.Index(fields=['farm', 'status'], name='invite_farm_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('phone_number', 'farm'), name='unique_pending_invite_per_phone_farm')],
            },
        ),
    ]
