# Generated by Django 6.1 on 2026-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_pending_invite_per_phone_farm',
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('farm__isnull', False), ('status', 'PENDING')), fields=('phone_number', 'farm'), name='unique_pending_invite_per_phone_farm'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('farm__isnull', True), ('status', 'PENDING')), fields=('phone_number',), name='unique_pending_external_invite_per_phone'),
        ),
    ]
