# Generated by Django 6.1 on 2026-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_invitation_unique_pending_invite_per_phone_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='business_name',
            field=models.CharField(blank=True, help_text='External partners only. Carried onto the FarmPartnerLink.', max_length=150),
        ),
    ]
