# Generated by Django 6.1 on 2026-09-06 10:08

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOwnerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'farm owner account',
                'verbose_name_plural': 'farm owner accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
