# Generated by Django 6.1 on 2026-08-20 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms_farm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Farm Owner'), ('MANAGER', 'Farm Manager'), ('WORKER', 'Farm Worker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='farms.farm')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms_membership',
                'ordering': ['farm', 'role', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_farm_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='farmmembership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='farmmembership',
            index=models.Index(fields=['farm', 'role'], name='membership_farm_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='farmmembership',
            constraint=models.UniqueConstraint(fields=('farm', 'user'), name='unique_membership_per_farm_user'),
        ),
    ]
