# Generated by Django 6.1 on 2026-08-21 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_owner_name', models.CharField(blank=True, max_length=150)),
                ('to_owner_name', models.CharField(blank=True, max_length=150)),
                ('transferred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='farms.farm')),
                ('from_owner', models.ForeignKey(blank=True, help_text='Null for the original registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_transferred_away', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_transfers_performed', to=settings.AUTH_USER_MODEL)),
                ('to_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_transferred_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm ownership history',
                'db_table': 'farms_ownership_history',
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['farm', '-transferred_at'], name='ownership_farm_time_idx')],
            },
        ),
    ]
