# Generated by Django 6.1 on 2026-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farmownershiphistory'),
        ('production', '0004_inventoryitem_inventorystockin_inventoryusagelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmembership',
            name='houses',
            field=models.ManyToManyField(blank=True, help_text='Houses this member may record against. Empty means all.', related_name='assigned_memberships', to='production.house'),
        ),
    ]
