# Generated by Django 6.1 on 2026-09-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0003_farmmembership_houses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('purpose', models.CharField(choices=[('INVITATION', 'Invitation PIN'), ('LOW_STOCK', 'Low stock alert')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='farms.farm')),
            ],
            options={
                'db_table': 'notifications_sms_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['purpose', 'status'], name='sms_purpose_status_idx'), models.Index(fields=['related_farm', 'purpose', 'sent_at'], name='sms_farm_purpose_time_idx')],
            },
        ),
    ]
