# Generated by Django 6.1 on 2026-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmmembership_houses'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smslog',
            name='sms_farm_purpose_time_idx',
        ),
        migrations.AddField(
            model_name='smslog',
            name='context_key',
            field=models.CharField(blank=True, default='', help_text='Dedupe key: for a low-stock alert, the sorted comma-joined ids of the items it named. Blank for an invitation, which has nothing to dedupe against.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['related_farm', 'purpose', 'context_key', 'sent_at'], name='sms_dedupe_idx'),
        ),
    ]
